# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXmrKpFetM5HV8TUA_SKwr_LVBqTUCod
"""

import numpy as np
a = np.array([1,2,3,4,5,6])
print (a)

import numpy as np
a = np.array([1,2,3,4,5,'2'])
print (a)

np_arr = np.array([3,3,3,3,3.3,'hello',False])
print(np_arr)
print(bool(np_arr[-1]))

a=False
print(bool(a))

a='0'
print(bool(a))

a=0
print(bool(a))

import numpy as np
a = np.zeros((2,3,4))
# a = np.ones((2,3,4))
print(a)
print(type(a[0][0][0]))

import numpy as np
a = np.empty((4), dtype=int)
print(a)

a = np.full(4,5, dtype=int)
print(a)

import numpy as np
a = np.arange(3,12,1)
b=np.linspace(3,12,5, dtype=int)
print(b)

import numpy as np
my_grid = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
# 1. Using shape
print("Shape of the grid:", my_grid.shape)
# Output: (2, 3)
# 2. Using size
print("Size of the grid:", my_grid.size)
# Output: 6

import random
a = random.randint(1, 6)
print(a)

import random
a = ["Alice", "Bob", "Charlie", "Diana"]
winner = random.choice(a)
print(winner)

import numpy as np
a=np.random.randint(1,7,2)
print(a)
# giving value between any range

a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b) #power

import numpy as np

# Corrected spelling: randint
a = np.random.randint(2, 15, 5)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
b=a.reshape(5,1)
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

import numpy as np
# a=np.concatenate(([1, 2, 3],[4, 5, 6]))
# print(a)
a=np.random.randint(2,15,6)
b=np.random.randint(2,15,6)
print(np.concatenate((a,b),))

import numpy as np
a=np.transpose(np.array([[1,2,3],
                         [4,5,6]]))
print(a)

a=np.random.randint(2,15,6)
b=np.random.randint(1,19,6)
print(a)
print(b)
c=np.where(b > 2,b,a)
print(c)

import numpy as np
a = np.array([12, 4, 7, 4, 9, 1, 15])
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])
print(np.sort(a))
print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))
print(np.unique(a))
print(np.matmul(matrix_a, matrix_b))

import numpy as np
CRICKET_SCORE=np.array([67,54,78,92,67,78,90,26])
print("NO OF MATCHES PLAYED->",np.size(CRICKET_SCORE))
print("MAXIMUM SCORE IS->",np.max(CRICKET_SCORE))
print("MINIMUM SCORE IS->",np.min(CRICKET_SCORE))
print("STANDARD DEVIATION IS->",np.std(CRICKET_SCORE))
print("TOTAL SCORE IS->",np.sum(CRICKET_SCORE))
print("AVERAGE SCRE IS->",np.mean(CRICKET_SCORE))

import numpy as np
num_items = int(input("How many grocery items do you want to enter? "))

items_list = []
prices_list = []

print("\n--- Enter Grocery Details ---")
for i in range(num_items):

    item_name = input(f"Enter the name for item {i + 1}: ")
    item_price = float(input(f"Enter the price for {item_name}: $"))

    items_list.append(item_name)
    prices_list.append(item_price)

items = np.array(items_list)
prices = np.array(prices_list)

if num_items > 0:

    sort_indices = np.argsort(prices)

    sorted_items = items[sort_indices]
    sorted_prices = prices[sort_indices]

    print("\n--- Sorted Groceries (Cheapest to Most Expensive) ---")
    for item, price in zip(sorted_items, sorted_prices):
        print(f"{item}: ${price:.2f}")

    max_price = np.max(prices)
    min_price = np.min(prices)
    sd_price = np.std(prices)

    highest_price_index = np.argmax(prices)
    most_expensive_item = items[highest_price_index]

    print("\n--- Shop Statistics ---")
    print(f"Maximum Price: ${max_price:.2f}")
    print(f"Minimum Price: ${min_price:.2f}")
    print(f"Standard Deviation (SD): ${sd_price:.2f}")
    print(f"Premium Item: The most expensive item is {most_expensive_item} at ${max_price:.2f}")

else:
    print("\nNo items were entered. Exiting shop analyzer.")

import numpy as np
items = []
prices = []
for i in range(5):
    name = input(f"Enter name of item {i+1}: ")
    price = float(input(f"Enter price of {name}: "))
    items.append(name)
    prices.append(price)
prices = np.array(prices)
max_price = np.max(prices)
min_price = np.min(prices)
mean_price = np.mean(prices)
std_price = np.std(prices)
max_item = items[np.argmax(prices)]
min_item = items[np.argmin(prices)]
print("\n----- Results -----")
print(f"Most expensive item : {max_item} (₹{max_price})")
print(f"Cheapest item       : {min_item} (₹{min_price})")
print(f"Average price       : ₹{mean_price:.2f}")
print(f"Standard Deviation  : ₹{std_price:.2f}")

import numpy as np
matrix = np.random.randint(1, 90, size=(5, 5))
print("matrix:\n",matrix)
row_means = np.mean(matrix, axis=1)
col_means = np.mean(matrix, axis=0)
print("Mean of Rows:\n",row_means)
print("Mean of Columns:\n",col_means)
matrix[matrix % 2 == 0] = -1
print("replacing even numbers with -1:\n",matrix)
sorted_matrix = np.sort(matrix, axis=1)
fully_sorted_matrix = np.sort(sorted_matrix, axis=0)
print("\n4. Matrix sorted row-wise and then column-wise:\n", fully_sorted_matrix)
row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("sum of rows:\n",row_sums)
print("sum of columns:\n",col_sums)

negative_counts = np.sum(fully_sorted_matrix < 0, axis=0)
print("negative matrix:\n",negative_counts)

import numpy as np
stock_mat=np.random.randint(20,80, size=(5,5))
print("stock mat:\n",stock_mat)
demand_mat=np.random.randint(20,100,size=(5,5))
print("demand mat:\n",demand_mat)
Remaining_stock=stock_mat - demand_mat
print("remaining stock:\n",Remaining_stock)
Remaining_stock[Remaining_stock<0]=0
print("replace -ve -> 0:\n",Remaining_stock)
total_shortage=np.sum(np.where(Remaining_stock<0,Remaining_stock,0))
print("total shortage:\n",total_shortage)
product_zeroes=np.sum(Remaining_stock==0)
print("product with zero stock:\n",product_zeroes)
sorted_remaning_stock=np.sort(Remaining_stock,axis=1)
print("sorted row-wise:\n",sorted_remaning_stock)

import pandas as pd
file_=pd.read_csv('student_data.csv', sep=',')
print(file_.head(10))

import pandas as pd
dct={
    'name': ['Tonr', 'Nick', 'Krish', 'Jack'],
    'age': [20, 21, 19, 18],
    'roll': [1, 2, 3, 4]
}
df=pd.DataFrame(dct)
display(df)
# index
# df=pd.DataFrame(dct,index=['a','b','c','d'])

import pandas as pd
df=pd.read_csv('student_data.csv')
# from 1st
# df.head()
# from last
# df.tail()
# give no. of rows and columns
# df.shape
# df.info()
# df.describe()
# df.columns
# df.index
# single column
# df['internet_usage']
# multi column
# df[['study_hours','internet_usage']]
# df.iloc[0: 5]
# it gives codition given in any column with any constant we want
# df.loc[df['study_hours']==11]
# df.loc[df['assignments_completed']== 8].iloc[1]
# df[df['assignments_completed']>3]
# df['age']=20

# to rename any columns
# df.rename(columns={'assignments_completed':'assignments'}, inplace=True)
# df
# remove row
# df = df.drop(1)
# df
# remive column
# del df["assignments_completed"]
# df
# df.dropna(axis=1)
# sorted_df = df.sort_values(by="study_hours")
# print(sorted_df)
# df.isnull() gives true on '0' and false on any other number
# df.notnull() gives true on any number and false on '0'
# df.fillna(0)

# HOMEWORK
# how to use lambda function inside sort
# IN TOMORROWS CLASS WORK ON THIS

import pandas as pd
df = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
})
print(df["City"].unique())
